name: Status Checks
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 22]
    name: Build and Test with Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: ${{ matrix.node }}
          registry-url: "https://npm.pkg.github.com"
          scope: "@noahm"
          cache: "yarn"

      - name: Init project
        run: yarn --immutable

      - name: Webpack Build
        run: yarn build

      - name: Unit Tests
        run: yarn test

  checks:
    runs-on: ubuntu-latest
    name: Lints
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://npm.pkg.github.com"
          scope: "@noahm"
          cache: "yarn"

      - name: Init project
        run: yarn --immutable

      - name: eslint
        run: yarn lint

      - name: prettier
        run: yarn format --check
