name: Build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16, 18]
    name: Build with node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: ${{ matrix.node }}
          registry-url: "https://npm.pkg.github.com"
          scope: "@noahm"
          cache: "yarn"

      - name: Init project
        run: yarn

      - name: Build library
        run: yarn build

      - name: Test library
        run: yarn test
